keys:
  - &thinkbook age1pehlv5avrwhnxyhhl0vw56j0etr7emuu423ux3rcl05yy4p0wshqzrjc9f
  - &homelab age17qfkz7yt04j8tl9d45m3lrl23jcjg2sgf4kdpddqduvmrl9ags0q4n0uz7
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *thinkbook
      - *homelab
