enable_audio_bell no
allow_hyperlinks yes
pixel_scroll yes
font_size 9
background_blur 15
background_opacity 0.85

map alt+h neighboring_window left
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right

map alt+n next_tab
map alt+p previous_tab

map ctrl+shift+enter launch --cwd=current
map ctrl+shift+t launch --cwd=current --type=tab

globinclude dank-*.conf
